# -*- coding: utf-8 -*-
"""Genetic_Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7NMZ8Hy5WWuTBaILrHG9SMouLgCcymu
"""

import random
import time
import tracemalloc

def fitness(board):
    n = len(board)

    diag1 = {}
    diag2 = {}

    attacks = 0

    for row in range(n):
        d1 = row - board[row]
        d2 = row + board[row]

        diag1[d1] = diag1.get(d1, 0) + 1
        diag2[d2] = diag2.get(d2, 0) + 1

    for count in diag1.values():
        if count > 1:
            attacks += count * (count - 1) // 2

    for count in diag2.values():
        if count > 1:
            attacks += count * (count - 1) // 2

    return attacks

def create_population(size, n):
    population = []

    for _ in range(size):
        board = list(range(n))
        random.shuffle(board)
        population.append(board)

    return population

def selection(population):
    tournament = random.sample(population, 5)
    tournament.sort(key=lambda x: fitness(x))
    return tournament[0]

def crossover(parent1, parent2):
    n = len(parent1)

    start = random.randint(0, n - 2)
    end = random.randint(start + 1, n - 1)

    child = [-1] * n

    child[start:end] = parent1[start:end]

    pointer = 0

    for num in parent2:
        if num not in child:
            while child[pointer] != -1:
                pointer += 1
            child[pointer] = num

    return child

def mutate(board, mutation_rate=0.1):
    board = board[:]

    if random.random() < mutation_rate:
        i = random.randint(0, len(board) - 1)
        j = random.randint(0, len(board) - 1)

        board[i], board[j] = board[j], board[i]

    return board

def genetic_algorithm(
    n,
    population_size=80,
    generations=1000,
    mutation_rate=0.15
):

    population = create_population(population_size, n)

    best_solution = None
    best_fitness = float("inf")

    for generation in range(generations):

        population.sort(key=lambda x: fitness(x))

        current_best = population[0]
        current_fitness = fitness(current_best)

        # Save Best Solution
        if current_fitness < best_fitness:
            best_solution = current_best
            best_fitness = current_fitness

        # Perfect Solution Found
        if current_fitness == 0:
            return current_best, generation, 0

        new_population = population[:10]

        while len(new_population) < population_size:
            parent1 = selection(population)
            parent2 = selection(population)

            child = crossover(parent1, parent2)
            child = mutate(child, mutation_rate)

            new_population.append(child)

        population = new_population

    return best_solution, generations, best_fitness


def print_board(board):
    n = len(board)

    for i in range(n):
        row = ["Q" if board[i] == j else "." for j in range(n)]
        print(" ".join(row))

test_cases = [10, 30, 50, 100, 200, 500]

for n in test_cases:

    print("\n" + "=" * 60)
    print(f"Solving {n}-Queens Problem Using Genetic Algorithm")
    print("=" * 60)

    tracemalloc.start()

    start_time = time.time()

    solution, generations, conflicts = genetic_algorithm(
        n=n,
        population_size=80,
        generations=1000,
        mutation_rate=0.15
    )

    end_time = time.time()

    current, peak = tracemalloc.get_traced_memory()

    tracemalloc.stop()

    print(f"\nBoard Size (N)   : {n}")
    print(f"Generations Used : {generations}")
    print(f"Conflicts        : {conflicts}")
    print(f"Execution Time   : {end_time - start_time:.4f} seconds")
    print(f"Peak Memory Used : {peak / 1024:.2f} KB")

    if conflicts == 0:
        print("Status           : Perfect Solution Found")
    else:
        print("Status           : Near Optimal Solution Found")

    # Print only small boards
    if n <= 20:
        print("\nChess Board Solution:\n")
        print_board(solution)